import json
CH="01_governance/project_atlas_charter_v1.0.md"; CUT="01_governance/cutover_strategy_v2.0.md"; SOW="01_governance/SOW_NRG-COB-2026-01_project_atlas.pdf"
RAID="03_raid/raid_log_2026-04-03.csv"; CL="04_change_requests/change_log.md"
CR3="04_change_requests/CR-003_store_inventory_api.md"; CR5="04_change_requests/CR-005_disaster_recovery_region.md"; CR7="04_change_requests/CR-007_go_live_replan.md"; CR8="04_change_requests/CR-008_loyalty_module.md"
SC1="05_meeting_minutes/2026-01-28_steerco_SC-01.md"; DMD="05_meeting_minutes/2026-02-18_data_migration_deep_dive.md"; SC2="05_meeting_minutes/2026-02-25_steerco_SC-02.md"; SC3="05_meeting_minutes/2026-03-04_steerco_SC-03_special.md"; VR="05_meeting_minutes/2026-03-11_databridge_vendor_review.md"; INT="05_meeting_minutes/2026-03-18_integration_sync.md"; SC4="05_meeting_minutes/2026-03-25_steerco_SC-04.md"
BUD="06_finance_resourcing/budget_burn_report_2026-03.pdf"; RES="06_finance_resourcing/resource_plan_v3.0.pdf"; HEL="07_reference/project_helios_lessons_learned_2024.md"
import datetime as dt
def SR(n): d=dt.date(2026,1,16)+dt.timedelta(7*(n-1)); return f"02_status_reports/status_report_wk{n:02d}_{d.isoformat()}.md"
def E(src,text): return {"source":src,"text":text}
Q=[]
def q(cat,question,answer,key_facts,evidence,features,answerable=True,history=None,trap=None):
    Q.append({"id":f"Q{len(Q)+1:02d}","category":cat,"question":question,"chat_history":history or [],"answerable":answerable,
              "reference_answer":answer,"key_facts":key_facts,"evidence":evidence,"features_tested":features,**({"trap":trap} if trap else {})})

# --- Simple factual lookup
q("factual","Who is the executive sponsor of Project Atlas?","Laura Bennett, CIO of Northwind Retail Group.",["Laura Bennett"],[E(CH,"Executive Sponsor: Laura Bennett, CIO")],["dense"])
q("factual","Who leads the data migration workstream?","Marcus Chen (Cobalt Systems) leads WS2 – Data Migration.",["Marcus Chen"],[E(CH,"WS2 – Data Migration Marcus Chen"),E(DMD,"Marcus Chen, WS2 Data Migration Lead")],["dense"])
q("factual","How long is the production cutover window?","48 hours.",["48"],[E(CH,"within a 48-hour cutover window"),E(CUT,"inside the 48-hour window")],["dense"])
q("factual","How much order history data needs to be migrated?","Approximately 2.3 TB of order history.",["2.3 TB"],[E(CH,"approximately 2.3 TB")],["dense"])
q("factual","What are the recovery point and recovery time objectives for disaster recovery?","RPO of 15 minutes and RTO of 4 hours, defined in CR-005 (Azure Central US DR region).",["15 minutes","4 hours"],[E(CR5,"Recovery Point Objective (RPO): 15 minutes"),E(SC2,"with an RPO of 15 minutes and an RTO of 4 hours")],["dense"])
q("table_pdf","What are the response and resolution targets for a P1 incident during hypercare?","P1 (order taking stopped in multiple stores or on e-commerce): 30-minute response, 4-hour resolution.",["30 minutes","4 hours"],[E(SOW,"Order taking stopped in multiple stores or on e-commerce")],["pdf_parsing","table"])
q("table_pdf","How much does Cobalt get paid when UAT is complete?","$1,200,000 (25% of the fixed price), payment milestone PM-3, tied to M5 UAT complete.",["1,200,000","25%"],[E(SOW,"M5 – UAT complete")],["pdf_parsing","table"])

# --- Exact ID / keyword (BM25 should win)
q("exact_id","What is the mitigation for RSK-014?","Weekly executive call with DataBridge (Kevin Walsh); service credits under SOW section 9.3; parallel evaluation of Azure Data Factory as a fallback, with a go/no-go on the fallback by 2026-04-24.",["Kevin Walsh","9.3","Azure Data Factory","2026-04-24"],[E(RAID,"Weekly executive call with DataBridge (Kevin Walsh)")],["bm25","hybrid"])
q("exact_id","What does SOW section 9.3 say?","It covers subcontractor delay service credits: 2% of DataBridge's monthly fees per full week of delay beyond a committed date, capped at 10%, with 100% passed through to Northwind as a reduction of Cobalt's next invoice.",["2%","10%","pass"],[E(SOW,"Subcontractor delay service credits"),E(VR,"Under SOW section 9.3, service credits accrue at 2%")],["bm25","hybrid","pdf_parsing"])
q("exact_id","Who owns RSK-016 and when is the related review scheduled?","David Okafor owns RSK-016 (PCI DSS sign-off for payment integration). The QSA review is booked for 2026-04-14.",["David Okafor","2026-04-14"],[E(RAID,"QSA review booked for 2026-04-14"),E(INT,"booked for 2026-04-14 (RSK-016)")],["bm25","hybrid"])
q("exact_id","What was ISS-012 and how was it fixed?","TLS certificates in the SIT environment expired (2026-03-16), breaking integration tests for two days. Certificates were renewed and automated renewal enabled through Azure Key Vault; closed 2026-03-18.",["certificate","Azure Key Vault"],[E(RAID,"TLS certificates in the SIT environment expired"),E(INT,"TLS certificates expired in the SIT environment")],["bm25","hybrid"])
q("exact_id","What is DEC-006?","The decision to adopt a hybrid cutover: pre-migrate historical orders older than 90 days ahead of cutover and migrate only open orders, the last 90 days and the final delta in the 48-hour window. Decided at special SteerCo SC-03 on 2026-03-04.",["hybrid","90 days","SC-03"],[E(RAID,"Adopt hybrid cutover approach"),E(SC3,"DEC-006: Adopt the hybrid cutover approach")],["bm25","hybrid"])
q("exact_id","What happened to CR-006?","CR-006 (extra performance test cycle, $60,000, raised by Marcus Chen) was superseded by CR-007 and closed at SC-03 on 2026-03-04.",["superseded","CR-007"],[E(CL,"Superseded by CR-007"),E(SC3,"CR-006 is closed as superseded by CR-007")],["bm25","hybrid"])

# --- Paraphrase (dense should win)
q("paraphrase","Are we worried about the migration tool supplier hitting their dates?","Yes. RSK-014 (High, open): DataBridge has slipped connector v3.2 from 2026-03-13 to 2026-04-30; further slippage would threaten mock run 1 and the 2026-08-17 go-live.",["v3.2","2026-04-30"],[E(RAID,"DataBridge Solutions has slipped delivery of Oracle connector v3.2")],["dense","query_rewrite"])
q("paraphrase","Why could orders end up linked to the wrong shoppers after the move?","Because of duplicates in the legacy customer master (RSK-011): profiling found a 12% duplicate rate, which could break order-to-customer matching. It was reduced to 4.5% by week 11, with a target below 1% before mock run 1.",["12%","customer master"],[E(RAID,"12% duplicate rate in the Meridian customer master"),E(SR(11),"Customer master duplicate rate reduced from 12% to 4.5%")],["dense"])
q("paraphrase","What's our plan B if the migration vendor lets us down again?","Azure Data Factory is being evaluated as a fallback migration tool (ACT-024 proof of concept, due 2026-04-24, 40% complete as of 2026-04-03).",["Azure Data Factory","2026-04-24"],[E(RAID,"Build a proof of concept migrating one month of order history using Azure Data Factory"),E(SR(12),"Azure Data Factory fallback proof of concept 40% complete")],["dense","query_rewrite"])

# --- Reasoning / reranking ("why" questions where many chunks mention the topic)
q("why_rerank","Why was the go-live date moved?","The 2026-02-17 performance test showed DataBridge Migrate (connector v3.1) at 18 GB/hour versus the 50 GB/hour needed to move 2.3 TB in the 48-hour window (ISS-009), and the v3.2 fix slipped to 2026-04-30. CR-007 moved go-live from 2026-06-15 to 2026-08-17 with a hybrid cutover.",["18 GB","50 GB","CR-007"],[E(CR7,"sustained only 18 GB per hour"),E(SC3,"Go-live moves from 2026-06-15 to 2026-08-17")],["rerank"])
q("why_rerank","Why was the loyalty integration request turned down?","CR-008 was rejected at SC-04 (2026-03-25) because it would jeopardize the 2026-08-17 go-live and add $410,000 while WS2 is already over budget; loyalty changes were also out of scope in the charter. Deferred to Phase 2.",["go-live","over budget","Phase 2"],[E(SC4,"rejected CR-008 for Phase 1"),E(CR8,"would put the re-planned go-live at risk")],["rerank"])
q("why_rerank","Why is the data migration workstream over budget?","Extended DataBridge performance testing after ISS-009 and two additional data engineering contractors for the customer master cleansing sprint (RSK-011). WS2 is at 133.3% of planned spend to date.",["performance testing","contractors","133"],[E(BUD,"two additional data engineering contractors engaged for the customer master cleansing sprint"),E(SC4,"two additional contractors for the customer master cleansing sprint")],["rerank","pdf_parsing"])

# --- Temporal / metadata filtering
q("temporal","What was the overall status in week 6, and why?","Red. The 2026-02-17 performance test achieved only 18 GB/hour vs 50 GB/hour required (ISS-009), putting the June 15 go-live at serious risk.",["Red","18 GB"],[E(SR(6),"Overall status is Red. The data migration performance test")],["metadata_filter"])
q("temporal","What was the program status in the report for the week ending 2026-02-06?","Amber (week 4): ExpressRoute provisioning delay (ISS-004) threatened M1, and DataBridge signalled a slip on connector v3.2 (RSK-014).",["Amber","ExpressRoute"],[E(SR(4),"Overall status moved to Amber")],["metadata_filter"])
q("temporal","When did the overall status first turn Red?","Week 6, the report for the week ending 2026-02-20, driven by the data migration throughput issue (ISS-009).",["week 6","2026-02-20"],[E(SR(6),"Overall status is Red."),E(SR(5),"Status remains Amber.")],["metadata_filter","multi_doc"])
q("temporal","What go-live date was being reported in the week 3 status report?","2026-06-15 (the original baseline, before CR-007).",["2026-06-15"],[E(SR(3),"Forecast go-live 2026-06-15")],["metadata_filter"],trap="Must NOT answer 2026-08-17; the question asks for the point-in-time value.")

# --- Recency / conflicting versions
q("recency","What is the current go-live date?","Monday 2026-08-17, approved through CR-007 at SC-03 on 2026-03-04 (originally 2026-06-15).",["2026-08-17"],[E(CR7,"Move production go-live from 2026-06-15 to 2026-08-17"),E(SR(12),"Go-live remains on track for 2026-08-17")],["recency","rerank"],trap="Charter and weeks 1-7 still say 2026-06-15.")
q("recency","What is the total approved budget now?","$5,345,000: the $4,800,000 baseline plus CR-003 ($85K), CR-005 ($140K) and CR-007 ($320K).",["5,345,000"],[E(CL,"Revised approved budget $5,345,000"),E(BUD,"The revised approved budget, including CR-003, CR-005 and CR-007, is $5,345,000")],["recency"],trap="Charter and SOW say $4,800,000.")
q("recency","When is data migration mock run 1 planned?","2026-05-08 (re-planned by CR-007; originally 2026-03-20).",["2026-05-08"],[E(CR7,"Data migration mock run 1 complete 2026-03-20 2026-05-08")],["recency"],trap="Charter says 2026-03-20.")
q("recency","Who is the lead data architect?","Ravi Shankar until his last day on 2026-04-17; Ana Gomez takes over as backfill, joining 2026-04-13 for a one-week overlap.",["Ravi Shankar","Ana Gomez","2026-04-13"],[E(RES,"Lead Data Architect (backfill)"),E(SR(12),"Ana Gomez joins on 2026-04-13 as lead data architect")],["recency","multi_doc"])
q("recency","What cutover approach is the program using?","A hybrid cutover (cutover strategy v2.0, DEC-006): about 2.0 TB of history older than 90 days is pre-migrated; only ~300 GB (open orders, last 90 days, final delta) moves in the 48-hour window. It replaced the v1.0 big bang approach.",["hybrid","90 days"],[E(CUT,"Supersedes Version 1.0 (2026-02-02, \"big bang\" cutover)"),E(CUT,"Historical orders older than 90 days (approximately 2.0 TB)")],["recency"],trap="Week 4 status mentions the v1.0 big bang approach.")

# --- Multi-hop
q("multi_hop","Which open risks affect the workstream that is over budget?","WS2 Data Migration is over budget (133.3% of plan). Its open risks are RSK-011 (customer master data quality, High), RSK-014 (DataBridge connector v3.2 slipping, High) and RSK-019 (lead data architect attrition, Medium). Open issue ISS-009 also sits in WS2.",["RSK-011","RSK-014","RSK-019"],[E(BUD,"One workstream, WS2 Data Migration, breaches the 10% over-budget tolerance"),E(RAID,"Data quality in legacy customer master"),E(RAID,"DataBridge connector v3.2 delivery slipping"),E(RAID,"Lead data architect attrition")],["multi_hop","pdf_parsing","bm25"])
q("multi_hop","Who approved CR-003, and why didn't it need the Steering Committee?","Tom Harris, the Client Program Director, approved it on 2026-02-11. Its $85,000 cost is below the $100,000 threshold and it had no milestone impact, so it fell within his delegated authority.",["Tom Harris","100,000"],[E(CR3,"Approved on 2026-02-11 by Tom Harris"),E(CH,"CRs with a cost impact below $100,000 and no milestone impact may be approved by the Client Program Director")],["multi_hop"])
q("multi_hop","What is the WS4 budget after the inventory API change, and how much has it spent so far?","Revised WS4 budget is $885,000 (baseline $800,000 + $85,000 for CR-003). Actual spend to date is $245,000 against $230,000 planned (106.5%, within tolerance).",["885","245"],[E(CR3,"WS4 budget increases from $800,000 to $885,000"),E(BUD,"Slightly ahead of plan because the store inventory availability API")],["multi_hop","pdf_parsing"])
q("multi_hop","What alternative to waiting for the vendor fix was considered when the go-live was re-planned, and what would it have cost?","Option C at SC-03: switch to Azure Data Factory immediately, with go-live on 2026-09-28 and a cost of $510,000. Option B (hybrid cutover, $320,000) was chosen.",["Azure Data Factory","510,000","2026-09-28"],[E(SC3,"Switch to Azure Data Factory now")],["multi_hop","rerank"])
q("multi_hop","Which workstream is the new lead data architect joining, who leads it, and when does she start?","Ana Gomez joins WS2 Data Migration, led by Marcus Chen, starting 2026-04-13.",["Ana Gomez","WS2","Marcus Chen","2026-04-13"],[E(RES,"Ana Gomez"),E(RAID,"backfill Ana Gomez joins on 2026-04-13")],["multi_hop","pdf_parsing"])

# --- Aggregation / calculation
q("aggregation","How many change requests have been approved, and what is their total cost?","Five: CR-001 ($0), CR-003 ($85,000), CR-004 ($0), CR-005 ($140,000) and CR-007 ($320,000), totalling $545,000.",["5","545,000"],[E(CL,"Move delivery sprints from 3-week to 2-week cadence"),E(CL,"Re-plan go-live to 2026-08-17 due to data migration throughput")],["aggregation","table"])
q("aggregation","What is the forecast overrun at completion?","$175,000 (3.3%) over the $5,345,000 revised budget, entirely in WS2 (EAC $5,520,000). DataBridge service credits could offset up to $48,000.",["175,000","WS2"],[E(BUD,"The program is forecast to finish $175,000 (3.3%) over the revised budget")],["aggregation","pdf_parsing"])
q("aggregation","By how many weeks did the go-live slip?","9 weeks (2026-06-15 to 2026-08-17).",["9 weeks"],[E(CR7,"Go-live moves 9 weeks")],["aggregation"])

# --- Distractor (similar project in corpus)
q("distractor","What was the original go-live date before it was moved?","2026-06-15 for Project Atlas (moved to 2026-08-17).",["2026-06-15"],[E(CR7,"Move production go-live from 2026-06-15 to 2026-08-17")],["rerank","metadata_filter"],trap="Helios lessons-learned says a go-live moved from 2024-09-09; that is a different project.")
q("distractor","How did the final program cost compare with the budget?","Project Atlas is not finished. As of 2026-03-31, spend is $1,955,000 vs $1,870,000 planned to date, and the forecast at completion is $5,520,000 vs the $5,345,000 revised budget (+$175,000).",["not finished","5,520,000"],[E(BUD,"Estimate at completion (EAC)")],["rerank","groundedness"],trap="Helios finished at $2.9M vs $2.5M budget; do not present that as Atlas.")

# --- No answer (should abstain)
q("no_answer","What is Northwind's current share price?","Not in the documents. The assistant should say it can't find this.",[],[],["guardrail"],answerable=False)
q("no_answer","What is DataBridge's hourly rate for their solutions engineer?","Not in the documents. The SOW rate card covers Cobalt roles only.",[],[],["guardrail"],answerable=False,trap="Rate card has Cobalt rates; must not borrow them for DataBridge.")
q("no_answer","When will Phase 2 go live?","Not in the documents. Only a Phase 2 loyalty business case due 2026-06-30 is mentioned.",[],[],["guardrail"],answerable=False)

# --- Conversational follow-ups
q("conversational","What risks does he own?","Arjun Mehta owns RSK-014 (DataBridge connector v3.2 slipping, High) and RSK-021 (go-live slipping into the retail freeze, Low), both open.",["RSK-014","RSK-021"],[E(RAID,"Go-live slipping into retail freeze"),E(RAID,"DataBridge connector v3.2 delivery slipping")],["history_aware","bm25"],
  history=[{"role":"user","content":"Who is the program manager?"},{"role":"assistant","content":"Arjun Mehta from Cobalt Systems is the program manager."}])
q("conversational","How much will it cost to run each month?","About $9,500 per month in Azure run cost for the standby DR resources (on top of the $140,000 one-time change cost).",["9,500"],[E(CR5,"estimated Azure run cost of $9,500 per month"),E(SC2,"additional Azure run cost of about $9,500 per month")],["history_aware"],
  history=[{"role":"user","content":"What is CR-005 about?"},{"role":"assistant","content":"CR-005 adds Azure Central US as a disaster recovery region for the order management platform, approved at SC-02 for $140,000."}])

# --- More PDF tables
q("table_pdf","What percentage of its planned spend to date has the application modernization workstream used?","90.4% (actual $470K vs planned $520K), due to two developer positions filled late in February.",["90.4"],[E(BUD,"Under plan due to two open developer positions filled late in February")],["pdf_parsing","table"])
q("table_pdf","How many data engineers are in the offshore data migration team?","6 data engineers in Chennai, plus 2 contractors for the cleansing sprint (Feb–Apr 2026).",["6","2 contractors"],[E(RES,"Plus 2 contractors for cleansing sprint")],["pdf_parsing","table"])

json.dump({"name":"Project Atlas RAG golden set","version":"1.0","corpus_root":"corpus/","num_questions":len(Q),"questions":Q},open("/home/claude/project-atlas/eval/golden_set.json","w"),indent=2,ensure_ascii=False)
print(len(Q))
