// Thin typed fetch wrapper. Response types come from schema.d.ts (generated by `make web-types`).
import type { components } from "./schema";

export type ReadyOut = components["schemas"]["ReadyOut"];
export type ProfileOut = components["schemas"]["ProfileOut"];

export async function getJson<T>(path: string): Promise<T> {
  const response = await fetch("/api" + path);
  if (!response.ok && response.status !== 503) {
    throw new Error(response.status + " " + response.statusText);
  }
  return (await response.json()) as T;
}
